name: CMake Build Matrix
on: 
  push:
  pull_request:
  release:
    # tags:
    # - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config: 
        - {
            name: "Ubuntu - GCC",
            os: ubuntu-latest,
            # build_type: "Release",
            cc: "gcc",
            cxx: "g++",
          }
        - {
            name: "macOS - Clang",
            os: macos-latest,
            # build_type: "Release",
            cc: "clang",
            cxx: "clang++",
          }

    steps:
      - uses: actions/checkout@v2

      - name: Print env
        run: |
          echo github.event.action: ${{ github.event.action }}
          echo github.event_name: ${{ github.event_name }}

      - name: Install dependencies on ubuntu
        if: startsWith(matrix.config.name, 'Ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install cmake
          cmake --version
          gcc --version

      - name: Install dependencies on macos
        if: startsWith(matrix.config.os, 'macOS')
        run: |
          brew install cmake
          cmake --version
          clang --version
          
      - name: Configure
        shell: bash
        run: |
          mkdir build
          mkdir install
          cmake \
            -S . \
            -B build \
            -DCMAKE_INSTALL_PREFIX:PATH=install

      - name: Build
        shell: bash
        # run: cmake --build build --config ${{ matrix.config.build_type }}
        run: cmake --build build

      - name: Install
        shell: bash
        run: cmake --install build --strip

      - name: Run App
        shell: bash
        run: ./install/bin/app

