name: Static Analysis
on:
  push:
  pull_request:

jobs:
  static_analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

- name: Run static analysis for C++ project
  uses: JacobDomagala/StaticAnalysis@v0.0.4
  with:
    # (Optional) clang-tidy args
    clang_tidy_args: -checks='*,fuchsia-*,google-*,zircon-*,abseil-*,modernize-use-trailing-return-type'

    # (Optional) cppcheck args
    cppcheck_args: --enable=all --suppress=missingInclude
